title: <p align="center"> Sandeep Srikanti </p>
logo: /assets/img/logo.png
description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/sandeepsrikanti">LinkedIn</a> |
  <a href="https://github.com/sandeepsrikanti">GitHub</a>
  
  <br>  
  IIT Madras & IIM Lucknow MBA graduate with 14+ Years of proven experience in Product Management & Strategic Product Marketing.
  Highly motivated professional with a passion for understanding customer needs, solving problems & developing products.
  Rich experience in utilizing Product & Customer Data - Data Science & Analytics (AI/ML) to extract valuable insights for guiding Product decisions and Marketing strategies.
  <br>
  </p>

show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
