title: <p align="center"> Sandeep Srikanti </p>
logo: /assets/img/logo.png
description:
  <p align="center">
  <a href="pdf/Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/sandeepsrikanti">LinkedIn</a> |
  <a href="https://github.com/sandeepsrikanti">GitHub</a>
  
  <br>  
  Highly motivated Data Science professional with a passion for understanding customer needs, 
  solving problems by extracting insights from data & developing products.
  <br>
  </p>

show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
