title: <p align="center"> Sandeep Srikanti </p>
logo: /assets/img/Profile.jpeg
description:
  <p align="center">
  <a href="pdf/Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/sandeepsrikanti">LinkedIn</a> |
  <a href="https://github.com/sandeepsrikanti">GitHub</a>
  

  </p>


theme: jekyll-theme-minimal
